"""Offline sample catalog — a diverse pool of unwatched titles to recommend *from*.

Lets the engine produce real rows (and E2E exercise the full pipeline) with zero TMDB/Trakt
credentials. Deliberately spans genres, eras, tones, and movie/show so re-ranker diversity and
swing slots have something to chew on. Seeded idempotently by ``tmdb_id`` (none of these clash
with the sample *history* in ``ingest/sample.py``: 438631 / 68718 / 95396).
"""

from __future__ import annotations

from sqlalchemy.orm import Session

from phare.catalog.service import upsert_titles
from phare.db.models import TitleKind
from phare.providers.types import TitleMetadata

# Real TMDB poster paths, keyed by tmdb_id, so the sample catalog shows actual artwork — even fully
# offline (the TMDB image CDN needs no API key). Without these the demo is a wall of text blocks,
# which is the first thing a new user sees on the sample-data path. Verified against the TMDB API;
# refresh if a title's primary poster ever changes.
_POSTERS: dict[int, str] = {
    329865: "/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    335984: "/qTcATCpiFDcgY8snQIfS2j0bFP7.jpg",
    264660: "/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg",
    157336: "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    238: "/kKjIYmvpBUIxcYJ0LL9YZwv4nrZ.jpg",
    8967: "/l8cwuB5WJSoj4uMAsnzuHBOMaSJ.jpg",
    120467: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    8363: "/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
    493922: "/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
    419430: "/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg",
    76341: "/tRxkZboyyXnFgCthoViWBwISZ0r.jpg",
    245891: "/sm7rZZivZm2NhJDucFf3gpfFdVt.jpg",
    120: "/oENY593nKRVL2PnxXsMtlh8izb4.jpg",
    6977: "/6d5XOczc226jECq0LIX0siKtgHR.jpg",
    210577: "/ts996lKsxvjkO2yiYG0ht4qAicO.jpg",
    146233: "/jsS3a3ep2KyBVmmiwaz3LvK49b1.jpg",
    129: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    324857: "/eD4bGQNfmqExIAzKdvX5gDHhI2.jpg",
    1396: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    1438: "/4lbclFySvugI51fwsyxBTOm4DqK.jpg",
    87108: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    60059: "/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    94997: "/7V0Ebks0GgpKvQ7QbLAIdX5dos4.jpg",
    46648: "/dC7jkj2g1aU8sxKqM6D4g44xA6w.jpg",
    28: "/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
    38: "/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    76: "/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg",
    78: "/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
    85: "/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    98: "/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg",
    101: "/bxB2q91nKYp8JNzqE7t7TWBVupB.jpg",
    115: "/3bv6WAp6BSxxYvB5ozKFUYuRA8C.jpg",
    128: "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    137: "/gCgt1WARPZaXnq523ySQEUKinCs.jpg",
    155: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    194: "/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
    279: "/gQRfiyfGvr1az0quaYyMram3Aqt.jpg",
    289: "/lGCEKlJo2CnWydQj7aamY7s1S7Q.jpg",
    582: "/cVUDMnskSc01rdbyH0tLATTJUdP.jpg",
    603: "/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
    670: "/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
    694: "/uAR0AWqhQL1hQa69UDEbb2rE5Wx.jpg",
    769: "/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg",
    807: "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    857: "/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
    949: "/e09dLw1Ljtccd2P4NsuUvVtS5du.jpg",
    1124: "/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
    1398: "/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg",
    1417: "/z7xXihu5wHuSMWymq5VAulPVuvg.jpg",
    1422: "/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    1920: "/lA9CNSdo50iQPZ8A2fyVpMvJZAf.jpg",
    1949: "/6YmeO4pB7XTh8P8F960O1uA14JO.jpg",
    4348: "/o8UhmEbWPHmTUxP0lMuCoqNkbB3.jpg",
    4638: "/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg",
    7345: "/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
    9693: "/k9IAS4TehZFcKi4HVByxZNPfqex.jpg",
    10193: "/AbbXspMOwdvwWZgVN0nabZq03Ec.jpg",
    10681: "/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    11324: "/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
    11423: "/jcgUjx1QcupGzjntTVlnQ15lHqy.jpg",
    14337: "/xEoq2WmDzpzxhkHEsmOYOg6BPg6.jpg",
    17654: "/tuGlQkqLxnodDSk6mp5c2wvxUEd.jpg",
    18239: "/k2qTooPlHffgNABNWxeJdGMglPK.jpg",
    27205: "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    36557: "/lMrxYKKhd4lqRzwUHAy5gcx9PSO.jpg",
    37165: "/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    37724: "/d0IVecFQvsGdSbnMAHqiYsNYaJT.jpg",
    37799: "/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    54344: "/NKJdryIFHr245Umq6gXsf7oULW.jpg",
    60622: "/a3VW6khsyUVKrG0GBCWFG3NzWPX.jpg",
    63639: "/5vQlVWkIMPhZ88OWchJsgwGEK9.jpg",
    64690: "/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    67070: "/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
    70523: "/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    76331: "/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    152601: "/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
    220289: "/ezUtb9m5DeLwL2gxi4gktzNCvQv.jpg",
    242224: "/qt3fqapeo94TfvMyld8P7gkpXLz.jpg",
    242582: "/j9HrX8f7GbZQm1BrBiR40uFQZSb.jpg",
    244786: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    270303: "/iwnQ1JH1wdWrGYkgWySptJ5284A.jpg",
    273481: "/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg",
    290098: "/dLlH4aNHdnmf62umnInL8xPlPzw.jpg",
    300668: "/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg",
    310131: "/zap5hpFCWSvdWSuPGAQyjUv2wAC.jpg",
    313369: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    324552: "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
    334541: "/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg",
    339403: "/tYzFuYXmT8LOYASlFCkaPiAFAl0.jpg",
    353081: "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    354912: "/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
    372058: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    374720: "/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
    376867: "/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg",
    399055: "/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg",
    426426: "/dtIIyQyALk57ko5bjac7hi01YQ.jpg",
    447332: "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    492188: "/2JRyCKaRKyJAVpsIHeLvPw5nHmw.jpg",
    496243: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    503919: "/yAKNmpcUweGH6WMCEWenwU9PsbE.jpg",
    505600: "/2aSxRDmisJP90H3S0aocyuQIe4z.jpg",
    515001: "/1mqL7VG4Ix8wmxwypmCA1HTHBky.jpg",
    530385: "/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    530915: "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    531428: "/rUDuOKpkKBHxx41BScqKej72iT3.jpg",
    546554: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
}


def _movie(
    tmdb_id: int,
    title: str,
    year: int,
    genres: list[str],
    keywords: list[str],
    runtime: int,
    popularity: float,
    overview: str,
) -> TitleMetadata:
    return TitleMetadata(
        kind=TitleKind.movie,
        tmdb_id=tmdb_id,
        title=title,
        year=year,
        genres=genres,
        keywords=keywords,
        runtime_minutes=runtime,
        popularity=popularity,
        overview=overview,
        poster_path=_POSTERS.get(tmdb_id),
    )


def _show(
    tmdb_id: int,
    title: str,
    year: int,
    genres: list[str],
    keywords: list[str],
    runtime: int,
    popularity: float,
    overview: str,
) -> TitleMetadata:
    return TitleMetadata(
        kind=TitleKind.show,
        tmdb_id=tmdb_id,
        title=title,
        year=year,
        genres=genres,
        keywords=keywords,
        runtime_minutes=runtime,
        popularity=popularity,
        overview=overview,
        poster_path=_POSTERS.get(tmdb_id),
    )


# Broader static pool so the offline demo has real neighbourhoods to recommend from — 24
# titles gave absurd 'because you watched' pairings (review A13). Resolved from TMDB (real
# ids + posters), keywords hand-curated. (tmdb_id, title, year, genres, keywords, runtime,
# popularity, overview)
_EXTRA_MOVIES: list[tuple] = [
    (
        603,
        "The Matrix",
        1999,
        ["Action", "Science Fiction"],
        ["simulation", "hacker", "dystopia"],
        136,
        51.8,
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    ),
    (
        27205,
        "Inception",
        2010,
        ["Action", "Science Fiction", "Adventure"],
        ["dreams", "heist", "subconscious"],
        148,
        59.7,
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    ),
    (
        1124,
        "The Prestige",
        2006,
        ["Drama", "Mystery", "Science Fiction"],
        ["magic", "rivalry", "obsession"],
        130,
        29.0,
        "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
    ),
    (
        9693,
        "Children of Men",
        2006,
        ["Science Fiction", "Thriller", "Action"],
        ["dystopia", "infertility", "hope"],
        109,
        22.5,
        "In 2027, in a chaotic world in which humans can no longer procreate, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea, where her child's birth may help scientists save the future of humankind.",
    ),
    (
        18239,
        "Moon",
        2009,
        ["Adventure", "Fantasy", "Drama", "Romance"],
        ["isolation", "clone", "space"],
        131,
        23.8,
        "Forks, Washington resident Bella Swan is reeling from the departure of her vampire love, Edward Cullen, and finds comfort in her friendship with Jacob Black, a werewolf. But before she knows it, she's thrust into a centuries-old conflict, and her desire to be with Edward at any cost leads her to take greater and greater risks.",
    ),
    (
        300668,
        "Annihilation",
        2018,
        ["Science Fiction", "Horror"],
        ["mutation", "expedition", "dread"],
        115,
        24.1,
        "A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.",
    ),
    (
        17654,
        "District 9",
        2009,
        ["Science Fiction"],
        ["aliens", "apartheid", "refugee"],
        112,
        24.8,
        "Thirty years ago, aliens arrive on Earth. Not to conquer or give aid, but to find refuge from their dying planet. Separated from humans in a South African area called District 9, the aliens are managed by Multi-National United, which is unconcerned with the aliens' welfare but will do anything to master their advanced technology. When a company field agent contracts a mysterious virus that begins to alter his DNA, there is only one place he can hide: District 9.",
    ),
    (
        152601,
        "Her",
        2013,
        ["Romance", "Science Fiction", "Drama"],
        ["loneliness", "artificial intelligence", "love"],
        126,
        9.2,
        "In the not so distant future, Theodore, a lonely writer, purchases a newly developed operating system designed to meet the user's every need. To Theodore's surprise, a romantic relationship develops between him and his operating system. This unconventional love story blends science fiction and romance in a sweet tale that explores the nature of love and the ways that technology isolates and connects us all.",
    ),
    (
        1417,
        "Pan's Labyrinth",
        2006,
        ["Fantasy", "Drama", "War"],
        ["fairy tale", "fascism", "childhood"],
        118,
        28.4,
        "In post–civil war Spain, 10-year-old Ofelia moves with her pregnant mother to live under the control of her cruel stepfather. Drawn into a mysterious labyrinth, she meets a faun who reveals that she may be a lost princess from an underground kingdom. To return to her true father, she must complete a series of surreal and perilous tasks that blur the line between reality and fantasy.",
    ),
    (
        399055,
        "The Shape of Water",
        2017,
        ["Drama", "Fantasy", "Romance"],
        ["creature", "cold war", "outsider"],
        123,
        6.7,
        "An other-worldly story, set against the backdrop of Cold War era America circa 1962, where a mute janitor working at a lab falls in love with an amphibious man being held captive there and devises a plan to help him escape.",
    ),
    (
        244786,
        "Whiplash",
        2014,
        ["Drama", "Music", "Thriller"],
        ["jazz", "ambition", "mentor"],
        107,
        25.5,
        "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    ),
    (
        313369,
        "La La Land",
        2016,
        ["Comedy", "Drama", "Romance"],
        ["jazz", "dreams", "los angeles"],
        129,
        15.3,
        "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    ),
    (
        496243,
        "Parasite",
        2019,
        ["Comedy", "Thriller", "Drama"],
        ["class", "con", "family"],
        133,
        35.2,
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    ),
    (
        670,
        "Oldboy",
        2003,
        ["Thriller", "Mystery"],
        ["revenge", "captivity", "twist"],
        120,
        13.3,
        "With no clue how he came to be imprisoned, drugged and tortured for 15 years, a desperate man seeks revenge on his captors.",
    ),
    (
        11423,
        "Memories of Murder",
        2003,
        ["Crime", "Drama", "Thriller"],
        ["serial killer", "investigation", "rural"],
        131,
        16.5,
        "A sadistic serial rapist and murderer of young women terrorizes a small province in 1980s South Korea. To prevent further crimes, three increasingly desperate detectives with conflicting methods race against time to unravel the violent mind of the killer in a futile effort to solve the case.",
    ),
    (
        1949,
        "Zodiac",
        2007,
        ["Crime", "Mystery", "Thriller"],
        ["serial killer", "obsession", "journalism"],
        157,
        24.5,
        "Over the course of a decade, editors of the San Francisco Chronicle entice themselves in the murders of the Zodiac Killer. However, as time runs its course, interest in the case dwindles in the eyes of the professionals. The Killer stops interacting with the public. However, believing he has the answers, an amateur cartoonist from the initial sightings races against time to prevent what he believes is another murder.",
    ),
    (
        807,
        "Se7en",
        1995,
        ["Crime", "Mystery", "Thriller"],
        ["serial killer", "sins", "noir"],
        127,
        24.7,
        'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Somerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
    ),
    (
        949,
        "Heat",
        1995,
        ["Crime", "Drama", "Action"],
        ["heist", "cat and mouse", "los angeles"],
        170,
        33.3,
        "Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.",
    ),
    (
        769,
        "Goodfellas",
        1990,
        ["Drama", "Crime"],
        ["mafia", "rise and fall", "loyalty"],
        145,
        24.3,
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    ),
    (
        1422,
        "The Departed",
        2006,
        ["Drama", "Thriller", "Crime"],
        ["undercover", "mole", "boston"],
        151,
        26.5,
        "To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there's a mole among them.",
    ),
    (
        64690,
        "Drive",
        2011,
        ["Drama", "Thriller", "Crime"],
        ["getaway driver", "neo-noir", "quiet"],
        100,
        9.6,
        "Driver is a skilled Hollywood stuntman who moonlights as a getaway driver for criminals. Though he projects an icy exterior, lately he's been warming up to a pretty neighbor named Irene and her young son, Benicio. When Irene's husband gets out of jail, he enlists Driver's help in a million-dollar heist. The job goes horribly wrong, and Driver must risk his life to protect Irene and Benicio from the vengeful masterminds behind the robbery.",
    ),
    (
        273481,
        "Sicario",
        2015,
        ["Action", "Crime", "Thriller"],
        ["cartel", "border", "moral grey"],
        122,
        26.5,
        "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
    ),
    (
        242582,
        "Nightcrawler",
        2014,
        ["Crime", "Drama", "Thriller"],
        ["media", "ambition", "los angeles"],
        118,
        11.4,
        "When Lou Bloom, desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant to become the star of his own story. Aiding him in his effort is Nina, a TV-news veteran.",
    ),
    (
        76341,
        "Mad Max: Fury Road",
        2015,
        ["Action", "Adventure", "Science Fiction"],
        ["post-apocalyptic", "chase", "desert"],
        121,
        37.4,
        "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
    ),
    (
        324552,
        "John Wick: Chapter 2",
        2017,
        ["Action", "Thriller", "Crime"],
        ["assassin", "revenge", "underworld"],
        122,
        27.5,
        "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
    ),
    (
        36557,
        "Casino Royale",
        2006,
        ["Adventure", "Action", "Thriller"],
        ["spy", "poker", "espionage"],
        144,
        27.1,
        "Le Chiffre, a banker to the world's terrorists, is scheduled to participate in a high-stakes poker game in Montenegro, where he intends to use his winnings to establish his financial grip on the terrorist market. M sends Bond—on his maiden mission as a 00 Agent—to attend this game and prevent Le Chiffre from winning. With the help of Vesper Lynd and Felix Leiter, Bond enters the most important poker game in his already dangerous career.",
    ),
    (
        353081,
        "Mission: Impossible - Fallout",
        2018,
        ["Action", "Adventure"],
        ["spy", "stunts", "chase"],
        147,
        25.6,
        "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
    ),
    (
        98,
        "Gladiator",
        2000,
        ["Action", "Drama", "Adventure"],
        ["rome", "revenge", "arena"],
        155,
        39.1,
        "After the death of Emperor Marcus Aurelius, his devious son takes power and demotes Maximus, one of Rome's most capable generals who Marcus preferred. Eventually, Maximus is forced to become a gladiator and battle to the death against other men for the amusement of paying audiences.",
    ),
    (
        155,
        "The Dark Knight",
        2008,
        ["Action", "Crime", "Thriller"],
        ["vigilante", "anarchy", "gotham"],
        152,
        45.9,
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    ),
    (
        37724,
        "Skyfall",
        2012,
        ["Action", "Adventure", "Thriller"],
        ["spy", "past", "loyalty"],
        143,
        24.2,
        "When Bond's latest assignment goes gravely wrong, agents around the world are exposed and MI6 headquarters is attacked. While M faces challenges to her authority and position from Gareth Mallory, the new Chairman of the Intelligence and Security Committee, it's up to Bond, aided only by field agent Eve, to locate the mastermind behind the attack.",
    ),
    (
        85,
        "Raiders of the Lost Ark",
        1981,
        ["Adventure", "Action"],
        ["archaeology", "nazis", "artifact"],
        115,
        14.9,
        "When Dr. Indiana Jones – the tweed-suited professor who just happens to be a celebrated archaeologist – is hired by the government to locate the legendary Ark of the Covenant, he finds himself up against the entire Nazi regime.",
    ),
    (
        120,
        "The Lord of the Rings: The Fellowship of the Ring",
        2001,
        ["Adventure", "Fantasy", "Action"],
        ["quest", "ring", "middle-earth"],
        179,
        52.4,
        "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
    ),
    (
        324857,
        "Spider-Man: Into the Spider-Verse",
        2018,
        ["Animation", "Action", "Adventure", "Science Fiction"],
        ["superhero", "multiverse", "coming of age"],
        117,
        27.2,
        'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
    ),
    (
        372058,
        "Your Name",
        2016,
        ["Animation", "Romance", "Drama"],
        ["body swap", "fate", "comet"],
        106,
        27.8,
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    ),
    (
        128,
        "Princess Mononoke",
        1997,
        ["Adventure", "Fantasy", "Animation"],
        ["nature", "spirits", "war"],
        134,
        18.4,
        "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
    ),
    (
        10681,
        "WALL·E",
        2008,
        ["Animation", "Family", "Science Fiction"],
        ["robot", "environment", "love"],
        98,
        28.3,
        "After hundreds of years doing what he was built for, WALL•E— a robot designed to clean up the earth—discovers a new purpose in life when he meets a sleek search robot named EVE. EVE comes to realize that WALL•E has inadvertently stumbled upon the key to the planet's future, and races back to space to report to the humans. Meanwhile, WALL•E chases EVE across the galaxy and sets into motion one of the most imaginative adventures ever brought to the big screen.",
    ),
    (
        354912,
        "Coco",
        2017,
        ["Family", "Animation", "Music", "Adventure"],
        ["music", "family", "afterlife"],
        105,
        24.2,
        "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.",
    ),
    (
        10193,
        "Toy Story 3",
        2010,
        ["Animation", "Family", "Comedy"],
        ["toys", "friendship", "growing up"],
        102,
        52.5,
        "Woody, Buzz, and the rest of Andy's toys haven't been played with in years. With Andy about to go to college, the gang find themselves accidentally left at a nefarious day care center. The toys must band together to escape and return home to Andy.",
    ),
    (
        8363,
        "Superbad",
        2007,
        ["Comedy"],
        ["high school", "friendship", "coming of age"],
        113,
        9.4,
        "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    ),
    (
        115,
        "The Big Lebowski",
        1998,
        ["Comedy", "Crime"],
        ["slacker", "mistaken identity", "bowling"],
        117,
        8.7,
        "Jeffrey 'The Dude' Lebowski, a Los Angeles slacker who only wants to bowl and drink White Russians, is mistaken for another Jeffrey Lebowski, a wheelchair-bound millionaire, and finds himself dragged into a strange series of events involving nihilists, adult film producers, ferrets, errant toes, and large sums of money.",
    ),
    (
        4638,
        "Hot Fuzz",
        2007,
        ["Crime", "Action", "Comedy"],
        ["cop", "small town", "parody"],
        121,
        8.4,
        "Former London constable Nicholas Angel finds it difficult to adapt to his new assignment in the sleepy British village of Sandford. Not only does he miss the excitement of the big city, but he also has a well-meaning oaf for a partner. However, when a series of grisly accidents rocks Sandford, Angel smells something rotten in the idyllic village.",
    ),
    (
        137,
        "Groundhog Day",
        1993,
        ["Romance", "Fantasy", "Comedy"],
        ["time loop", "redemption", "small town"],
        101,
        9.1,
        "A cynical TV weatherman, along with his idealistic producer and his sardonic cameraman, is sent to report on Groundhog Day in the small town of Punxsutawney, where he finds himself repeating the same day over and over.",
    ),
    (
        515001,
        "Jojo Rabbit",
        2019,
        ["Comedy", "War", "Drama"],
        ["childhood", "satire", "wwii"],
        108,
        6.5,
        "Jojo, a lonely German boy during World War II has his world shaken when he learns that his single mother is hiding a Jewish girl in their home. Influenced by a buffoonish imaginary version of Adolf Hitler, he begins to question his beliefs and confront the conflict between propaganda and his own humanity.",
    ),
    (
        120467,
        "The Grand Budapest Hotel",
        2014,
        ["Comedy", "Drama"],
        ["hotel", "caper", "whimsy"],
        100,
        11.4,
        "The Grand Budapest Hotel tells of a legendary concierge at a famous European hotel between the wars and his friendship with a young employee who becomes his trusted protégé. The story involves the theft and recovery of a priceless Renaissance painting, the battle for an enormous family fortune and the slow and then sudden upheavals that transformed Europe during the first half of the 20th century.",
    ),
    (
        505600,
        "Booksmart",
        2019,
        ["Comedy"],
        ["high school", "friendship", "one night"],
        102,
        4.1,
        "Two academic teenage superstars realize, on the eve of their high school graduation, that they should have worked less and played more. Determined to never fall short of their peers, the girls set out on a mission to cram four years of fun into one night.",
    ),
    (
        310131,
        "The Witch",
        2016,
        ["Horror"],
        ["folk horror", "puritan", "isolation"],
        92,
        9.3,
        "In 1630, a farmer relocates his family to a remote plot of land on the edge of a forest where strange, unsettling things happen. With suspicion and paranoia mounting, each family member's faith, loyalty and love are tested in shocking ways.",
    ),
    (
        270303,
        "It Follows",
        2015,
        ["Horror", "Mystery"],
        ["curse", "dread", "suburbia"],
        101,
        9.7,
        "A young woman is followed by an unknown supernatural force after a sexual encounter.",
    ),
    (
        242224,
        "The Babadook",
        2014,
        ["Drama", "Horror"],
        ["grief", "motherhood", "monster"],
        94,
        19.7,
        "A grieving single mother and her child fall into a deep well of paranoia when an eerie children's book manifests in their home.",
    ),
    (
        447332,
        "A Quiet Place",
        2018,
        ["Horror", "Drama", "Science Fiction"],
        ["silence", "family", "creatures"],
        91,
        27.8,
        "A family is forced to live in silence while hiding from creatures that hunt by sound.",
    ),
    (
        503919,
        "The Lighthouse",
        2019,
        ["Drama", "Fantasy", "Thriller"],
        ["isolation", "madness", "sea"],
        109,
        7.0,
        "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.",
    ),
    (
        530385,
        "Midsommar",
        2019,
        ["Horror", "Drama", "Mystery"],
        ["folk horror", "grief", "cult"],
        147,
        15.9,
        "Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets, gradually turns into a dark nightmare as the mysterious inhabitants invite them to participate in their disturbing festive activities.",
    ),
    (
        694,
        "The Shining",
        1980,
        ["Horror", "Thriller"],
        ["isolation", "madness", "hotel"],
        144,
        31.7,
        "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
    ),
    (
        289,
        "Casablanca",
        1943,
        ["Drama", "Romance"],
        ["wartime", "sacrifice", "nightclub"],
        102,
        8.4,
        "In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications.",
    ),
    (
        38,
        "Eternal Sunshine of the Spotless Mind",
        2004,
        ["Science Fiction", "Drama", "Romance"],
        ["memory", "breakup", "love"],
        108,
        18.1,
        "Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.",
    ),
    (
        76,
        "Before Sunrise",
        1995,
        ["Drama", "Romance"],
        ["one night", "conversation", "vienna"],
        101,
        15.0,
        "An unexpected meeting on a train leads two travelers to spend an evening wandering through Vienna. As the night unfolds, they share stories and conversations about life and love, exploring new ideas while a quiet intimacy grows between them, knowing it may be their only night together.",
    ),
    (
        531428,
        "Portrait of a Lady on Fire",
        2019,
        ["Drama", "Romance"],
        ["painting", "forbidden love", "18th century"],
        121,
        8.8,
        "On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.",
    ),
    (
        4348,
        "Pride & Prejudice",
        2005,
        ["Drama", "Romance"],
        ["regency", "class", "courtship"],
        128,
        18.3,
        "A story of love and life among the landed English gentry during the Georgian era. Mr. Bennet is a gentleman living in Hertfordshire with his overbearing wife and five daughters, but if he dies their house will be inherited by a distant cousin whom they have never met, so the family's future happiness and security is dependent on the daughters making good marriages.",
    ),
    (
        530915,
        "1917",
        2019,
        ["War", "History", "Drama"],
        ["wwi", "mission", "one shot"],
        119,
        10.6,
        "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
    ),
    (
        857,
        "Saving Private Ryan",
        1998,
        ["War", "Drama", "History"],
        ["wwii", "mission", "brotherhood"],
        169,
        44.9,
        "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
    ),
    (
        374720,
        "Dunkirk",
        2017,
        ["War", "Action", "Drama"],
        ["wwii", "evacuation", "survival"],
        107,
        9.6,
        "The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.",
    ),
    (
        28,
        "Apocalypse Now",
        1979,
        ["Drama", "War"],
        ["vietnam", "madness", "river"],
        147,
        16.8,
        'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, "does not exist, nor will it ever exist." His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.',
    ),
    (
        582,
        "The Lives of Others",
        2006,
        ["Drama", "Thriller"],
        ["surveillance", "cold war", "conscience"],
        137,
        6.9,
        "In 1984 East Berlin, dedicated Stasi officer Gerd Wiesler begins spying on a famous playwright and his actress-lover Christa-Maria. Wiesler becomes unexpectedly sympathetic to the couple, and faces conflicting loyalties when his superior takes a liking to Christa-Maria.",
    ),
    (
        7345,
        "There Will Be Blood",
        2007,
        ["Drama"],
        ["oil", "greed", "ambition"],
        158,
        23.1,
        "Ruthless silver miner, turned oil prospector, Daniel Plainview, moves to oil-rich California. Using his son to project a trustworthy, family-man image, Plainview cons local landowners into selling him their valuable properties for a pittance. However, local preacher Eli Sunday suspects Plainview's motives and intentions, starting a slow-burning feud that threatens both their lives.",
    ),
    (
        37799,
        "The Social Network",
        2010,
        ["Drama"],
        ["startup", "betrayal", "ambition"],
        121,
        12.2,
        "In 2003, Harvard undergrad and computer programmer Mark Zuckerberg begins work on a new concept that eventually turns into the global social network known as Facebook. Six years later, Mark is one of the youngest billionaires ever, but his unprecedented success leads to both personal and legal complications when he ends up on the receiving end of two lawsuits, one involving his former friend.",
    ),
    (
        492188,
        "Marriage Story",
        2019,
        ["Drama"],
        ["divorce", "family", "custody"],
        137,
        5.0,
        "A stage director and an actress struggle through a grueling, coast-to-coast divorce that pushes them to their personal extremes.",
    ),
    (
        334541,
        "Manchester by the Sea",
        2016,
        ["Drama"],
        ["grief", "family", "guilt"],
        138,
        6.1,
        "After his older brother passes away, Lee Chandler is forced to return home to care for his 16-year-old nephew. There he is compelled to deal with a tragic past that separated him from his family and the community where he was born and raised.",
    ),
    (
        376867,
        "Moonlight",
        2016,
        ["Drama"],
        ["identity", "coming of age", "miami"],
        111,
        6.3,
        "The tender, heartbreaking story of a young man’s struggle to find himself, told across three defining chapters in his life as he experiences the ecstasy, pain, and beauty of falling in love, while grappling with his own sexuality.",
    ),
    (
        37165,
        "The Truman Show",
        1998,
        ["Comedy", "Drama"],
        ["reality tv", "identity", "surveillance"],
        103,
        21.6,
        "In a picture-perfect seaside town, an insurance salesman begins to realize that his entire existence may be staged and observed by a vast unseen audience as part of a long-running real-time reality TV show.",
    ),
    (
        194,
        "Amélie",
        2001,
        ["Comedy", "Romance"],
        ["whimsy", "paris", "kindness"],
        122,
        11.2,
        "At a tiny Parisian café, the adorable yet painfully shy Amélie accidentally discovers a gift for helping others. Soon Amelie is spending her days as a matchmaker, guardian angel, and all-around do-gooder. But when she bumps into a handsome stranger, will she find the courage to become the star of her very own love story?",
    ),
    (
        129,
        "Spirited Away",
        2001,
        ["Animation", "Family", "Fantasy"],
        ["spirits", "coming of age", "bathhouse"],
        125,
        36.7,
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    ),
    (
        6977,
        "No Country for Old Men",
        2007,
        ["Crime", "Thriller", "Western"],
        ["chase", "fate", "west texas"],
        122,
        30.1,
        "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
    ),
    (
        146233,
        "Prisoners",
        2013,
        ["Drama", "Thriller", "Crime"],
        ["abduction", "desperation", "investigation"],
        153,
        13.9,
        "Keller Dover is facing every parent’s worst nightmare. His six-year-old daughter, Anna, is missing, together with her young friend, Joy, and as minutes turn to hours, panic sets in. The only lead is a dilapidated RV that had earlier been parked on their street.",
    ),
    (
        210577,
        "Gone Girl",
        2014,
        ["Mystery", "Thriller", "Drama"],
        ["marriage", "disappearance", "media"],
        149,
        20.0,
        "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    ),
    (
        11324,
        "Shutter Island",
        2010,
        ["Drama", "Thriller", "Mystery"],
        ["asylum", "twist", "investigation"],
        138,
        31.8,
        "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane, but his efforts are compromised by troubling visions and a mysterious doctor.",
    ),
    (
        546554,
        "Knives Out",
        2019,
        ["Comedy", "Crime", "Mystery"],
        ["whodunit", "family", "detective"],
        131,
        13.1,
        "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
    ),
    (
        78,
        "Blade Runner",
        1982,
        ["Science Fiction", "Drama", "Thriller"],
        ["replicant", "noir", "dystopia"],
        118,
        28.6,
        "In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.",
    ),
    (
        14337,
        "Primer",
        2004,
        ["Science Fiction", "Drama", "Thriller"],
        ["time travel", "engineers", "paradox"],
        77,
        3.0,
        "A group of fledgling inventors discover a complex method to manipulate reality. At first, they successfully game the stock market with it, but the consequences of the invention start to catch up with them.",
    ),
    (
        220289,
        "Coherence",
        2014,
        ["Thriller", "Science Fiction"],
        ["parallel worlds", "dinner party", "comet"],
        89,
        6.1,
        "Four couples gather for dinner the night a mysterious and powerful comet passes overhead.",
    ),
    (
        1398,
        "Stalker",
        1979,
        ["Science Fiction", "Drama"],
        ["the zone", "faith", "journey"],
        162,
        5.8,
        "Near a gray and unnamed city is the Zone, a place guarded by barbed wire and soldiers, and where the normal laws of physics are victim to frequent anomalies. A stalker guides two men into the Zone, specifically to an area in which deep-seated desires are granted.",
    ),
    (
        290098,
        "The Handmaiden",
        2016,
        ["Thriller", "Drama", "Romance"],
        ["con", "period", "betrayal"],
        145,
        18.4,
        "1930s Korea, in the period of Japanese occupation, a new girl, Sook-hee, is hired as a handmaiden to a Japanese heiress, Hideko, who lives a secluded life on a large countryside estate with her domineering Uncle Kouzuki. But the maid has a secret. She is a pickpocket recruited by a swindler posing as a Japanese Count to help him seduce the Lady to steal her fortune.",
    ),
    (
        279,
        "Amadeus",
        1984,
        ["Drama", "History", "Music"],
        ["mozart", "rivalry", "genius"],
        160,
        6.6,
        "Disciplined Italian composer Antonio Salieri becomes consumed by jealousy and resentment towards the hedonistic and remarkably talented young Salzburger composer Wolfgang Amadeus Mozart.",
    ),
    (
        339403,
        "Baby Driver",
        2017,
        ["Action", "Crime"],
        ["getaway driver", "heist", "soundtrack"],
        113,
        11.5,
        "After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.",
    ),
    (
        101,
        "Léon: The Professional",
        1994,
        ["Crime", "Drama", "Action"],
        ["hitman", "unlikely bond", "revenge"],
        111,
        18.1,
        "Léon, the top hit man in New York, has earned a rep as an effective \"cleaner\". But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda's thoughts turn to revenge, and she considers following in Léon's footsteps.",
    ),
    (
        426426,
        "Roma",
        2018,
        ["Drama"],
        ["family", "mexico city", "1970s"],
        135,
        2.4,
        "In 1970s Mexico City, two domestic workers help a mother of four while her husband is away for an extended period of time.",
    ),
]
_EXTRA_SHOWS: list[tuple] = [
    (
        54344,
        "The Leftovers",
        2014,
        ["Sci-Fi & Fantasy", "Drama"],
        ["grief", "rapture", "faith"],
        100,
        25.4,
        "When 2% of the world's population abruptly disappears without explanation, the world struggles to understand just what they're supposed to do about it. This is the story of the people who didn't make the cut.",
    ),
    (
        60059,
        "Better Call Saul",
        2015,
        ["Crime", "Drama"],
        ["law", "transformation", "prequel"],
        100,
        89.2,
        'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    ),
    (
        60622,
        "Fargo",
        2014,
        ["Crime", "Drama"],
        ["small town", "murder", "dark comedy"],
        100,
        87.1,
        "A close-knit anthology series dealing with stories involving malice, violence and murder based in and around Minnesota.",
    ),
    (
        1438,
        "The Wire",
        2002,
        ["Crime", "Drama"],
        ["baltimore", "institutions", "drugs"],
        100,
        65.5,
        "Told from the points of view of both the Baltimore homicide and narcotics detectives and their targets, the series captures a universe in which the national war on drugs has become a permanent, self-sustaining bureaucracy, and distinctions between good and evil are routinely obliterated.",
    ),
    (
        87108,
        "Chernobyl",
        2019,
        ["Drama"],
        ["disaster", "truth", "soviet"],
        100,
        32.2,
        "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
    ),
    (
        70523,
        "Dark",
        2017,
        ["Crime", "Drama", "Sci-Fi & Fantasy", "Mystery"],
        ["time travel", "town", "families"],
        100,
        45.5,
        "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.",
    ),
    (
        63639,
        "The Expanse",
        2015,
        ["Drama", "Mystery", "Sci-Fi & Fantasy"],
        ["space", "politics", "conspiracy"],
        100,
        60.0,
        "A thriller set two hundred years in the future following the case of a missing young woman who brings a hardened detective and a rogue ship's captain together in a race across the solar system to expose the greatest conspiracy in human history.",
    ),
    (
        46648,
        "True Detective",
        2014,
        ["Drama", "Mystery"],
        ["investigation", "philosophy", "louisiana"],
        100,
        67.3,
        "An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.",
    ),
    (
        67070,
        "Fleabag",
        2016,
        ["Comedy", "Drama"],
        ["grief", "family", "fourth wall"],
        100,
        13.1,
        "A portrait into the mind of a dry-witted, sexual, angry, porn-watching, grief-riddled woman, trying to make sense of the world. As she hurls herself headlong at modern living, Fleabag is thrown roughly up against the walls of contemporary London, with all its frenetic energy, late nights, and bright lights.",
    ),
    (
        76331,
        "Succession",
        2018,
        ["Drama", "Comedy"],
        ["power", "family", "media"],
        100,
        51.7,
        "Follow the lives of the Roy family as they contemplate their future once their aging father begins to step back from the media and entertainment conglomerate they control.",
    ),
    (
        1398,
        "The Sopranos",
        1999,
        ["Crime", "Drama"],
        ["mafia", "therapy", "family"],
        100,
        107.4,
        "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.",
    ),
    (
        1920,
        "Twin Peaks",
        1990,
        ["Drama", "Mystery"],
        ["small town", "surreal", "murder"],
        100,
        48.0,
        "The body of Laura Palmer is washed up on a beach near the small Washington state town of Twin Peaks. FBI Special Agent Dale Cooper is called in to investigate her strange demise only to uncover a web of mystery that ultimately leads him deep into the heart of the surrounding woodland and his very own soul.",
    ),
]


_RAW_CATALOG: list[TitleMetadata] = [
    *(_movie(*row) for row in _EXTRA_MOVIES),
    *(_show(*row) for row in _EXTRA_SHOWS),
    _movie(
        329865,
        "Arrival",
        2016,
        ["Science Fiction", "Drama"],
        ["aliens", "linguistics", "time"],
        116,
        35.0,
        "A linguist races to communicate with extraterrestrial visitors.",
    ),
    _movie(
        335984,
        "Blade Runner 2049",
        2017,
        ["Science Fiction", "Mystery"],
        ["replicant", "dystopia", "neo-noir"],
        164,
        40.0,
        "A young blade runner uncovers a secret that could plunge society into chaos.",
    ),
    _movie(
        264660,
        "Ex Machina",
        2014,
        ["Science Fiction", "Thriller"],
        ["artificial intelligence", "android", "isolation"],
        108,
        22.0,
        "A programmer is invited to administer a Turing test on an intelligent humanoid robot.",
    ),
    _movie(
        157336,
        "Interstellar",
        2014,
        ["Science Fiction", "Adventure"],
        ["wormhole", "space", "time dilation"],
        169,
        80.0,
        "Explorers travel through a wormhole in search of a new home for humanity.",
    ),
    _movie(
        238,
        "The Godfather",
        1972,
        ["Drama", "Crime"],
        ["mafia", "family", "power"],
        175,
        70.0,
        "The aging patriarch of a crime dynasty transfers control to his reluctant son.",
    ),
    _movie(
        8967,
        "There Will Be Blood",
        2007,
        ["Drama"],
        ["oil", "greed", "ambition"],
        158,
        18.0,
        "A ruthless prospector builds an empire during Southern California's oil boom.",
    ),
    _movie(
        120467,
        "The Grand Budapest Hotel",
        2014,
        ["Comedy", "Drama"],
        ["whimsical", "heist", "concierge"],
        99,
        28.0,
        "A legendary concierge and his protege are framed for murder.",
    ),
    _movie(
        8363,
        "Superbad",
        2007,
        ["Comedy"],
        ["coming of age", "high school", "friendship"],
        113,
        20.0,
        "Two co-dependent high schoolers scheme to buy alcohol for a party.",
    ),
    _movie(
        493922,
        "Hereditary",
        2018,
        ["Horror", "Mystery"],
        ["grief", "occult", "family secrets"],
        127,
        30.0,
        "A grieving family is haunted by tragic and disturbing occurrences.",
    ),
    _movie(
        419430,
        "Get Out",
        2017,
        ["Horror", "Thriller"],
        ["social commentary", "hypnosis", "suburbia"],
        104,
        33.0,
        "A young man uncovers a disturbing secret on a visit to his girlfriend's family.",
    ),
    _movie(
        76341,
        "Mad Max: Fury Road",
        2015,
        ["Action", "Adventure", "Science Fiction"],
        ["post-apocalyptic", "chase", "desert"],
        120,
        55.0,
        "A drifter and a rebel flee a tyrant across a wasteland in a war rig.",
    ),
    _movie(
        245891,
        "John Wick",
        2014,
        ["Action", "Thriller"],
        ["assassin", "revenge", "gun-fu"],
        101,
        60.0,
        "A retired hitman seeks vengeance for the killing of his dog.",
    ),
    _movie(
        120,
        "The Lord of the Rings: The Fellowship of the Ring",
        2001,
        ["Fantasy", "Adventure"],
        ["quest", "middle earth", "ring"],
        178,
        65.0,
        "A hobbit sets out to destroy a powerful ring and the dark lord who forged it.",
    ),
    _movie(
        6977,
        "No Country for Old Men",
        2007,
        ["Western", "Crime", "Thriller"],
        ["chase", "money", "fate"],
        122,
        24.0,
        "A hunter stumbles on drug-deal money and is pursued by a relentless killer.",
    ),
    _movie(
        210577,
        "Gone Girl",
        2014,
        ["Mystery", "Thriller", "Drama"],
        ["marriage", "missing person", "media"],
        149,
        38.0,
        "A man becomes the prime suspect in the disappearance of his wife.",
    ),
    _movie(
        146233,
        "Prisoners",
        2013,
        ["Thriller", "Crime", "Drama"],
        ["abduction", "moral dilemma", "investigation"],
        153,
        26.0,
        "A father takes matters into his own hands when his daughter goes missing.",
    ),
    _movie(
        129,
        "Spirited Away",
        2001,
        ["Animation", "Fantasy", "Family"],
        ["spirits", "coming of age", "magic"],
        125,
        50.0,
        "A girl wanders into a world of spirits and must work to free her parents.",
    ),
    _movie(
        324857,
        "Spider-Man: Into the Spider-Verse",
        2018,
        ["Animation", "Action", "Adventure"],
        ["multiverse", "superhero", "coming of age"],
        117,
        58.0,
        "A teen becomes Spider-Man and meets heroes from parallel dimensions.",
    ),
    _show(
        1396,
        "Breaking Bad",
        2008,
        ["Drama", "Crime"],
        ["chemistry teacher", "drugs", "transformation"],
        47,
        90.0,
        "A chemistry teacher turns to manufacturing drugs after a cancer diagnosis.",
    ),
    _show(
        1438,
        "The Wire",
        2002,
        ["Drama", "Crime"],
        ["police", "baltimore", "institutions"],
        60,
        40.0,
        "The drug trade in Baltimore seen through the eyes of law enforcement and dealers.",
    ),
    _show(
        87108,
        "Chernobyl",
        2019,
        ["Drama", "History"],
        ["disaster", "nuclear", "cover-up"],
        60,
        45.0,
        "A dramatization of the 1986 nuclear disaster and the sacrifices to contain it.",
    ),
    _show(
        60059,
        "Better Call Saul",
        2015,
        ["Drama", "Crime"],
        ["lawyer", "prequel", "moral decline"],
        47,
        52.0,
        "The transformation of a small-time lawyer into a morally flexible attorney.",
    ),
    _show(
        94997,
        "House of the Dragon",
        2022,
        ["Drama", "Fantasy", "Action"],
        ["dragons", "succession", "civil war"],
        60,
        85.0,
        "The Targaryen dynasty fractures into a war of succession over the throne.",
    ),
    _show(
        46648,
        "True Detective",
        2014,
        ["Drama", "Crime", "Mystery"],
        ["detectives", "occult", "anthology"],
        55,
        36.0,
        "Detectives chase a ritualistic killer across decades in Louisiana.",
    ),
]


def _dedupe(metas: list[TitleMetadata]) -> list[TitleMetadata]:
    """Drop repeats by (tmdb_id, kind) — a few curated titles also appear in the broader pool."""
    seen: set[tuple[int | None, TitleKind]] = set()
    out: list[TitleMetadata] = []
    for meta in metas:
        key = (meta.tmdb_id, meta.kind)
        if key not in seen:
            seen.add(key)
            out.append(meta)
    return out


_SAMPLE_CATALOG: list[TitleMetadata] = _dedupe(_RAW_CATALOG)


def sample_catalog_metas() -> list[TitleMetadata]:
    """The sample catalog as metadata (used by the evaluation personas)."""
    return list(_SAMPLE_CATALOG)


def seed_sample_catalog(session: Session) -> int:
    """Seed the offline sample catalog. Idempotent; returns the number of titles created."""
    return upsert_titles(session, _SAMPLE_CATALOG)
